### ISSUE TITLE
Action is producing warnings

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/ansible-test-gh-action#41]
There are deprecation warnings when using this action: `Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: test-summary/action`

That action is called by this one (https://github.com/ansible-community/ansible-test-gh-action/blob/main/action.yml#L442).

**Comment by webknjaz** [comment]
So this should be reported there, then.

**Comment by webknjaz** [comment]
> So this should be reported there, then.

https://github.com/test-summary/action/issues/15

**Comment by felixfontein** [comment]
Now there are also a lot of warnings due to `set-output` being deprecated.

**Comment by webknjaz** [comment]
Yeah, I know. I've made the update elsewhere: [re-actors/alls-green@`v1.2.1...v1.2.2`#diff-4ef72e27cf](https://github.com/re-actors/alls-green/compare/v1.2.1...v1.2.2#diff-4ef72e27cf831a0b512839bc73461043ac20e3c0a692c4dd1b5846cb25f69651R20-R29). Just haven't yet had time to address it here too :)
