### ISSUE TITLE
tests/output/reports/coverage=sanity.xml': No such file or directory

### ISSUE THREAD

**Issue by alexanderbazhenoff** [ansible-community/ansible-test-gh-action#77]
Hi, I'm bringing up [my collection](https://github.com/alexanderbazhenoff/ansible-collection-linux/tree/1_1_10) to all standards using this GH action. Everything from 2.10 to 2.17 is fine but [I see](https://github.com/alexanderbazhenoff/ansible-collection-linux/actions/runs/8527458025/job/23358936763) an errpr with sanity.xml file:

```
  Codecov report uploader 0.7.2
[2024-04-02T18:12:49.019Z] ['info'] => Project root located at: /home/runner/work/ansible-collection-linux/ansible-collection-linux
[2024-04-02T18:12:49.020Z] ['info'] -> No token specified or token is empty
[2024-04-02T18:12:49.093Z] ['info'] Searching for coverage files...
[2024-04-02T18:12:49.125Z] ['error'] None of the following appear to exist as files: ansible_collections/alexanderbazhenoff/linux/tests/output/reports/coverage=sanity=*.xml
[2024-04-02T18:12:49.126Z] ['error'] There was an error running the uploader: Error while cleaning paths. No paths matched existing files!
[2024-04-02T18:12:49.126Z] ['info'] Codecov will exit with status code 0. If you are expecting a non-zero exit code, please pass in the `-Z` flag
```
and finally:
```
ls: cannot access 'ansible_collections/alexanderbazhenoff/linux/tests/output/reports/coverage=sanity.xml': No such file or directory
```
The whole log is [on pastebin](https://pastebin.com/7YYmSXRr).

I have read [about covedecov.yml](https://github.com/ansible-collections/collection_template/blob/main/codecov.yml) then [created them](https://github.com/alexanderbazhenoff/ansible-collection-linux/blob/1_1_10/codecov.yml), but still an error. 

Yes, I don't use integration or unit tests there, because I have an ansible-molecule tests. May be there will be no coverage for sanity testing with ansible-test. I have also created a codecov token. But at least how to workaround an issue? Can you please a share an URL what I missed from documentation of ansible-test?

Thanks in advance.
```[tasklist]
### Tasks
```

**Comment by alexanderbazhenoff** [comment]
@felixfontein thank you a for a quick reaction.

Can I disable them forcibility by an option now to prevent this warning?

**Comment by felixfontein** [comment]
You can set `coverage` to `never` (https://github.com/ansible-community/ansible-test-gh-action/blob/main/README.md#coverage).

**Comment by webknjaz** [comment]
@felixfontein I didn't realize that roles-only collections don't produce coverage. Perhaps it's worth sticking a warning in the docs?

**Comment by alexanderbazhenoff** [comment]
> @felixfontein I didn't realize that roles-only collections don't produce coverage. Perhaps it's worth sticking a warning in the docs?

If I didn't run any of integration tests, there will be nothing to count the coverage from :) I think it's more ansible-test docs, not GH actions :)

Anyway I didn't get the whole question, but let me explain the whole situation of ansible-test documentations. Yes, some documentation about ansible-test is improved (at least last 3 years), but still there is no detailed examples on integration tests making. It's more theoretical and the whole concept. In other hand, ansible molecule was ready to use 3 years ago: it's includes a lot of drivers to create instances (docker, kubernetes, kvm, etc...), while I need to guess how to orchestrate them before using integration tests using ansible-test. That's why I think only sanity and unit tests (for ansible modules) are usefull in ansible-test. Also I need to guest who to set coverage, reading the docs and google a lot for another blogs - it's not so obvious and 'ready to use'.

**Comment by felixfontein** [comment]
Sanity tests also produce coverage results for plugins and modules. There's no way to generate coverage for roles AFAIK.

**Comment by alexanderbazhenoff** [comment]
> I created a PR to add a note for the `coverage` option: #78.

Thank you.
