### ISSUE TITLE
Specific target for integration tests

### ISSUE THREAD

**Issue by mamercad** [ansible-community/ansible-test-gh-action#8]
How do I limit the target of the integration tests (suppose there's a situation where you might not want to run all of them)?

**Comment by webknjaz** [comment]
Looks like there's a PR now potentially solving this: https://github.com/ansible-community/ansible-test-gh-action/pull/9.

**Comment by webknjaz** [comment]
@mamercad you can test this feature with `@unstable/v1` now and I'll release it under stable later.

**Comment by mamercad** [comment]
> @mamercad you can test this feature with `@unstable/v1` now and I'll release it under stable later.

Ah thanks, testing, will report back.

**Comment by mamercad** [comment]
Doesn't seem to work; we have this many tests:

```
❯ find tests/integration/targets -depth 1 | wc -l
      34
```

Here's what I'm trying:

```
❯ GIT_PAGER=cat git diff main -- .github/workflows/ansible-test-integration.yml
diff --git a/.github/workflows/ansible-test-integration.yml b/.github/workflows/ansible-test-integration.yml
index f7ac49c..ff7d239 100644
--- a/.github/workflows/ansible-test-integration.yml
+++ b/.github/workflows/ansible-test-integration.yml
@@ -21,9 +21,10 @@ jobs:
 
     steps:
       - name: Perform testing
-        uses: ansible-community/ansible-test-gh-action@release/v1
+        uses: ansible-community/ansible-test-gh-action@unstable/v1
         with:
           # ansible-core-version:
+          target: digital_ocean_account_info
           pre-test-cmd: >-  # Configure integration test run
             DO_API_KEY=${{ secrets.DO_API_KEY }}
             ./tests/utils/render.sh
```

From the Action logs, here's what it's doing:

```
/home/runner/.local/bin/ansible-test integration -v --color --docker --coverage --retry-on-error --continue-on-error --diff --python 3.8 -- digital_ocean_account_info
```

Results in:

```
ERROR: Command "docker exec 66042b706d4c367c997f85b5909526f7e28c483f260e5b53b88e7c8892ec5271 /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/community/digitalocean LC_ALL=en_US.UTF-8 /usr/bin/python3.8 /root/ansible/bin/ansible-test integration -v --coverage --retry-on-error --continue-on-error --diff --python 3.8 -- digital_ocean_account_info --metadata tests/output/.tmp/metadata-lry200em.json --truncate 0 --redact --color yes --requirements --coverage-label docker-default --allow-destructive" returned exit status 1.
```

Seems like we need to remove the argument separator `--`; works without it (only tested this locally).

**Comment by webknjaz** [comment]
Interesting... When I tried locally, using `--` worked but I don't think I added `--docker`. Usually, `--` is a separator for positional args that mustn't be parsed as options but it sounds like there's a bug with `ansible-test` constructing a command to run in a container.

I wonder if @mattclay has something to say about it...

FWIW I'll drop it for now.

**Comment by mamercad** [comment]
Running the tests in Docker is probably best (controlled environment); moreover, [the docs](https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html#running-integration-tests) are written with this in mind as well.

**Comment by webknjaz** [comment]
Sure. I was mostly curious where the bug with incorrect posargs bypass originates. A quick `git grep` of `ansible/ansible@devel` wasn't very helpful.

**Comment by webknjaz** [comment]
@mamercad I've added an extra commit on top, mind testing?

**Comment by klando** [comment]
Note that I went without issue by removing the double dash: https://github.com/ansible-community/ansible-test-gh-action/pull/11

**Comment by webknjaz** [comment]
@klando Oh, I missed it and have already pushed a similar commit to unstable: https://github.com/ansible-community/ansible-test-gh-action/commit/efc65d9e19608b9cc65199c9de10a6a29c807198.

**Comment by mattclay** [comment]
`ansible-test` does not support use of `--` with any of the delegation options (`--docker`, `--venv`, etc.).

**Comment by webknjaz** [comment]
@mattclay but I'd say it's a bug. Is it unreasonable to expect this from such a tool?

**Comment by klando** [comment]
last minute: I already see a point in providing several targets...
At the moment, I have both:
```
target: ${{ matrix.target }}                                                     # 1 element
target: ${{ fromJSON(needs.changes.outputs.targets) }}     # list
```

So maybe change and use `targets` or make it even more obvious that it respects `ansible-test` and that several targets can be used ?

**Comment by mamercad** [comment]
> @mamercad I've added an extra commit on top, mind testing?

Sure, I'll check shortly!

**Comment by mamercad** [comment]
```
Download action repository 'ansible-community/ansible-test-gh-action@unstable/v1' (SHA:3c9805ce9ea5ffbbc053f7ad0f21165ac7cf89cc)
```

```
+ /home/runner/.local/bin/ansible-test integration -v --color --docker --coverage --retry-on-error --continue-on-error --diff --python 3.8 digital_ocean_account_info
```

```
...
-        uses: ansible-community/ansible-test-gh-action@release/v1
+        uses: ansible-community/ansible-test-gh-action@unstable/v1
         with:
           # ansible-core-version:
+          target: digital_ocean_account_info
...
```

Working nicely for me!

**Comment by klando** [comment]
```
target: ${{ matrix.target }}    # 1 element
target: ${{ join( fromJSON( needs.changes.outputs.targets ), ' ') }}   # list
```

a `join` is required.

**Comment by webknjaz** [comment]
> a `join` is required.

Unless you save it as a list right away.

**Comment by webknjaz** [comment]
Released under v1.3.0.

**Comment by mamercad** [comment]
Thank you! 🎉

**Comment by mattclay** [comment]
> @mattclay but I'd say it's a bug. Is it unreasonable to expect this from such a tool?

@webknjaz The issue with `--` is addressed in https://github.com/ansible/ansible/pull/78328
